plugins {
    id 'com.android.application'
}

android {
    namespace 'ir.mahestan.block'
    compileSdk 35

    defaultConfig {
        applicationId 'ir.mahestan.block'
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName "2.0"
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.14.0'
}
